services:
  - type: web
    name: arthub-chat-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CONNECTION_URL
        sync: false
      - key: TOKEN_KEY
        sync: false
      - key: MAIN_API_URL
        sync: false
      - key: INTERNAL_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false 